### ISSUE TITLE
Give advice for when not to use vcr

### ISSUE THREAD

**Issue by sckott** [ropensci-books/http-testing#1]
anyone correct me if you think behavior should be different:

not to use vcr:

- when you expect an HTTP error response, e.g., with `worrms::wm_children(44444)`, which unfortunately gives a 204 response instead of a 404, and no response body

**Comment by maelle** [comment]
is this still valid?

**Comment by sckott** [comment]
I don't know actually. Probably not necessary

**Comment by maelle** [comment]
Cf https://github.com/maelle/exemplighratia/pull/10

**Comment by maelle** [comment]
Checks passing in https://github.com/maelle/exemplighratia/pull/10 so it means this issue is now obsolete.
