### ISSUE TITLE
PDF and epub links in Preamble direct to 'Page not found'

### ISSUE THREAD

**Issue by karissawhiting** [ropensci-books/http-testing#101]
I noticed the links to the [PDF](https://books.ropensci.org/http-testing/main.pdf) and [epub](https://books.ropensci.org/http-testing/main.epub) versions of the book in the [Preamble](https://books.ropensci.org/http-testing/#preamble) are directing to 'Page not found' and wanted to bring it to your attention. 

Thank you for this wonderful resource!

**Comment by maelle** [comment]
:wave: @karissawhiting! Thanks a ton, good catch! I'm not sure why I had removed those. They're back up, thanks again!
