### ISSUE TITLE
Use releases and publish to Zenodo

### ISSUE THREAD

**Issue by PietrH** [ropensci-books/http-testing#106]
The rOpenSci developers guide uses releases on github, and uses the Zenodo integration to publish to Zenodo. Meaning that there is a long term archive of the contents. 

Here it is: https://zenodo.org/records/6619350

I love that there is a doi available as well as an easy citation. I believe it would make this work more findable and ensure it'll remain available in the long term. 

Is there a reason not to do this that I am overlooking? 

Let me know if you need any help!

**Comment by sckott** [comment]
Thanks @PietrH !

What do you think @maelle ?

**Comment by maelle** [comment]
Thanks @PietrH!

This sounds good, let me set this up.

**Comment by PietrH** [comment]
Great! This will allow me to cite the book with a DOI in some software guidelines I'm drafting :smile:

**Comment by sckott** [comment]
Thanks @maelle !

**Comment by sckott** [comment]
#107

**Comment by maelle** [comment]
I am still fighting Zenodo, let's see if I win in the end (it appears I must create `CITATION.cff`, which I did, but now this file must be somewhat wrong and as usual Zenodo error messages aren't very specific)

**Comment by PietrH** [comment]
You probably know already, but just in case I'll drop these tidbits here;

```R

citation::cff2zenodo()

```

https://docs.ropensci.org/cffr/

- What error are you getting? 
- Is there a PR linked to this issue?

**Comment by maelle** [comment]
Thanks @PietrH! Thanks to @albansagouis (in the rOpenSci slack) I ended removing the Zenodo metadata and it worked!

**Comment by maelle** [comment]
I was literally coming to the issue to share the good news :grin: https://github.com/ropensci-books/http-testing?tab=readme-ov-file#http-testing-in-r-book now has a badge

**Comment by PietrH** [comment]
Superb! Thank you so much! I'll be citing it:

`Chamberlain, S., & Salmon, M. (2024). HTTP testing in R (v1.0.5). rOpenSci. https://doi.org/10.5281/zenodo.10608847`

I believe the use of `.zenodo.json` is officially unsupported as per [the {citation} documentation](https://search.r-project.org/CRAN/refmans/citation/html/citation2zenodo.html), we are having some trouble ourselves supporting multiple affiliations it for [the checklist package](https://github.com/inbo/checklist/).

Thanks for turning this around so quickly!

**Comment by maelle** [comment]
Thank _you_ for this suggestion and for citing the book!

Do CITATION.cff files support multiple affiliations maybe?
