### ISSUE TITLE
httr2 now supported in vcr/webmockr 

### ISSUE THREAD

**Issue by sckott** [ropensci-books/http-testing#108]
- [x] make any changes to note that `vcr` supports `httr2`
- [x] make any changes to note that `webmockr` supports `httr2`
- [ ] add examples of using `vcr` and/or `webmockr` with `httr2`?

Maybe other things that should be changed/mentioned ...

cc @maelle

**Comment by sckott** [comment]
Files to change:

- [ ] `03-mocking.Rmd`
- [ ] `04-webmockr-stubs.Rmd`
- [ ] `08-vcr-usage.Rmd`

> This also works with `httr`. The only difference is that you write to disk with a function `httr::write_disk(path)` rather than a parameter.

Anything to say about `httr2`?

- [ ] `wholegames-comparison.Rmd`

**Comment by maelle** [comment]
do you want to make a PR? :smile_cat:

**Comment by maelle** [comment]
yes I will have time to review!

**Comment by sckott** [comment]
Thanks!
