### ISSUE TITLE
Present horror scenarios

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#13]
E.g. an API introducing rate limiting without notification.

Not sure we need to name APIs having done so, but just saying these things can happen is important.

**Comment by sckott** [comment]
yes, good idea. and good thing we have a recent example - we can hide the name to protect the naïve

**Comment by maelle** [comment]
linked to #14

**Comment by maelle** [comment]
Too bad I won't have it ready by Halloween, a scary chapter would include

* API introducing rate limiting without notifications :spider: 
* API disappearing :ghost: 
* Emails from CRAN :scream: 
* others?
