### ISSUE TITLE
add example of keeping secret when auth is done via an OAuth token

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#15]

**Comment by sckott** [comment]
i'm not sure i know *exactly* what you mean - can you give an example?

**Comment by maelle** [comment]
related to #2 
(i.e. how do you perform tests and keep cassettes secure when there is an OAuth token)

**Comment by sckott** [comment]
Are you talking about an interactive OAuth flow where a browser tab opens, etc.? Or where a user sets their token using R options or an env var?

**Comment by maelle** [comment]
The package author would keep their token secure after generating it interactively, but one should make sure there's no secret in the stored cassettes (I am not sure it'd be very different from the API key stuff, but I want to write an example to see how things go).

**Comment by sckott** [comment]
good idea

**Comment by maelle** [comment]
things will be easier after https://github.com/ropensci/vcr/issues/58
