### ISSUE TITLE
how best to test a package that has  two auth methods

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#16]
Quite particular, maybe too special, am working on a package with both OAuth and an API key (either one or the other, from the user perspective).

**Comment by sckott** [comment]
hmm, i'm not sure we'll be able to support oauth in vcr/webmockr, but maybe, no one's brought it up yet. 

but in general in terms of two different auth methods, are the two methods in one function? Or different functions?

**Comment by maelle** [comment]
Same functions. 

And yes I am yet to try testing with vcr when using oauth. The token changes all the time (the access token expires after 6 hours for the API I wrap for instance). So it will influence caching/matching and also the secret keeping (i.e. how to recgonize the string not to be put in the fixtures, like for api keys).

**Comment by sckott** [comment]
Oof, this is a tough one. I guess it will be httr only.  Any way I can test it out myself so I can make sure it works in vcr and webmockr? I guess I can just test with any oauth perhaps, but there's different types of oauth. 

I don't think vcr is setup to handle a secret that changes. Do you think it would make sense to match against a regex for oauth? Does the oauth token have a consistent pattern?

**Comment by maelle** [comment]
I think it's a bit niche after all.
