### ISSUE TITLE
add notes about cassette names

### ISSUE THREAD

**Issue by sckott** [ropensci-books/http-testing#17]
see https://github.com/ropensci/vcr/issues/116 and https://github.com/ropensci/vcr/blob/check-cassette-names/R/check_cassette_names.R#L12-L21

**Comment by sckott** [comment]
We now mention `check_cassette_names` here https://books.ropensci.org/http-testing/vcr.html#setup - do you thin that's adequate @maelle ?

**Comment by maelle** [comment]
yep
