### ISSUE TITLE
Fixtures size and CRAN

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#18]
From a comment by @florianm in https://github.com/ropensci/software-review/issues/335#issuecomment-579092243

I was wondering whether the book could add advice on how to deal with http testing an CRAN. 

Should one not include fixtures when submitting to CRAN, and set the vcr off global variable to the contrary of ON_CRAN?

**Comment by florianm** [comment]
Another use case are included images in vignettes. E.g. the vignette displays example data including photos. Unless we can host and hot-link those photos, they have to be included in the package, inflating package size even some more (even if enthusiastically resized to the smallest possible image size). A real world value is 1MB for all image assets combined. Example: [rGeoCBI](https://dbca-wa.github.io/rGeoCBI/) shows photos in map popups in a [vignette](https://dbca-wa.github.io/rGeoCBI/articles/analysis.html#visualise). This serves as a working example to go from data to map popups, best done with real (although resized) data. Getting the images [included](https://github.com/dbca-wa/rGeoCBI/blob/master/vignettes/analysis.Rmd#L10) in the tic-generated docs requires some [incantations](https://github.com/dbca-wa/rGeoCBI/blob/master/data-raw/make_data.R) in the correct order. I might have summoned Jim Hester a few times by accident trying to permutate those spells.

A last use case are rich vignettes with leaflet maps - leaflet with plugins can add another 3MB to the docs size. Maybe deploying docs with tic might save us a folder like [this](https://github.com/dbca-wa/ruODK/tree/master/docs/articles/odata_files) in the CRAN version of a package?

**Comment by maelle** [comment]
for rOpenSci packages you get a pkgdown website cf https://ropensci.org/technotes/2019/06/07/ropensci-docs/

Note that this is the repo of the book about http testing Scott's been working on (sorry, that was unclear since I gave no context!)

**Comment by sckott** [comment]
thanks @maelle and @florianm 

we do have a small section discussing vcr and CRAN https://books.ropensci.org/http-testing/vcr-intro.html#vcr-enabled-tests-on-cran It definitely needs more work though, and we can include the option of setting vcr to off, etc. 

### Additional CRAN/vcr section items

- [ ] cassette (aka fixture) size
- [ ] cached file size (files cached when writing to disk) and contents
- [ ] turning vcr off - eg.., `VCR_TURN_OFF`, et al.

what else?

i'm assuming that test fixtures/files are included in the 5mb size limit for pkgs, but check on this

**Comment by maelle** [comment]
reg fixture size, once it exists link to https://github.com/ropensci/vcr/pull/201
