### ISSUE TITLE
rm docs/ and deploy with e.g. GH actions?

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#19]

**Comment by sckott** [comment]
sure - if you help me. do you have an example?

**Comment by maelle** [comment]
yesss I'm glad you ask. 

* https://speakerdeck.com/jimhester/github-actions-for-r?slide=40

* https://github.com/ropensci-org/blog-guidance for a not so good (no caching) but more complete (PR preview) setup

**Comment by maelle** [comment]
Notes to self

* Create empty GH pages branch.
* Then add workflow !!make it work for PDF and epub!!
* Then delete docs/ , build.sh, deploy.sh, Travis.yml
* Deactive repo on Travis
* Add rOpenSci CSS to style.css
* Create empty Netlify website
* Add Scott as maintainer of that website
* Add workflow for PRs
* Test that workflow by replacing "w/" with "with".

**Comment by maelle** [comment]
@sckott I can't find the repo to deactivate on Travis.

**Comment by maelle** [comment]
Remaining TODOs

- [ ] Deactivate the repo on Travis (Scott)

- [ ] #21

**Comment by sckott** [comment]
i dont know of any travis builds for this - looked at travis dot org and it's not turned on for this repo, so I think we're good

**Comment by maelle** [comment]
But why was there a Travis config file?

**Comment by sckott** [comment]
i don't remember now, could have been from a previous stage when i was using travis

**Comment by maelle** [comment]
* commit to master -> deploy to gh-pages
* commit in a PR from a branch of this repo -> deploy to Netlify, preview URL as commit comment
* commit in a PR from a fork -> book built (so one would notice something breaking the book) but no deploy (unless the two Netlify secrets, access token and a site ID, are set in the fork repo settings)

I hope it'll now work smoothly, @sckott!

**Comment by sckott** [comment]
thanks so much!

**Comment by maelle** [comment]
You're welcome, I like playing with this!
