### ISSUE TITLE
security chapter

### ISSUE THREAD

**Issue by sckott** [ropensci-books/http-testing#2]

**Comment by sckott** [comment]
e.g. pkgs to demo 

- https://github.com/ropensci/rredlist/tree/with-vcr scenario: API key in query param
- https://github.com/ropensci/microdemic scenario: API key as header

**Comment by sckott** [comment]
Add recent change in chapter: 

- https://github.com/ropensci/vcr/pull/90/files "dont print secrets in error block"

**Comment by maelle** [comment]
what would be the goal of this chapter compared to e.g. the dev guide security chapter?

**Comment by sckott** [comment]
we do already have a security chapter started, see https://books.ropensci.org/http-testing/security.html

goal is strictly security with respect to not exposing keys/secrets - i think we can link to the devguide chapter, but some items we wouldn't cover in that chapter in the dev guide that we would cover here I think

**Comment by maelle** [comment]
it'll be a point in the whole games and comparison chapters, but might warrant a whole chapter indeed.

**Comment by maelle** [comment]
something about workflows for encrypting/decrypting e.g. OAuth tokens for real requests would be useful. Cf https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html
