### ISSUE TITLE
Add terminology somewhere?

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#20]
I.e. https://github.com/ropensci/vcr#terminology

**Comment by sckott** [comment]
good idea

**Comment by maelle** [comment]
with also stub, mock, match on etc. 

Maybe an intro chapter could be

Why bother: why bother, who the book is for.
Actors: the concepts (terminology) and the packages.

**Comment by maelle** [comment]
it is in the vcr section actually
