### ISSUE TITLE
add benchmark of tests run with/without VCR_TURN_OFF?

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#28]

**Comment by sckott** [comment]
this is the idea you mentioned using a demo package, yes?

**Comment by maelle** [comment]
I should add that to the whole game chapters!

**Comment by maelle** [comment]
actually there's timing in vcr usage (in vcr docs), and the time saved is very much package-dependent, so I'm not sure it'd add much to have a benchmark.
