### ISSUE TITLE
Section on design of the package, sorta like drake's design chapter

### ISSUE THREAD

**Issue by sckott** [ropensci-books/http-testing#30]
https://books.ropensci.org/drake/design.html

think it's warranted since both webmockr and vcr are quite complex

**Comment by maelle** [comment]
you mean a section of the book would be for folks interested in contributing/understand how things work?

**Comment by sckott** [comment]
Right, for those that want to get a better understanding of how a request flows through the package, to either contribute or if they just want to understand better why they get vcr or webmockr errors

**Comment by maelle** [comment]
what'd also be interesting, given how much influence it has on the design, would be a paragraph (or more!) on your experience dealing with web APIs.
E.g. the fact that with vcr cassettes are recorded automatically and not edited might come from Ruby vcr, but also from what you find most appropriate given your experience.

**Comment by sckott** [comment]
Design of vcr I think simply follows Ruby's library, but I do like mostly the way it works. I guess i've not had experience manually editing cassettes/or other similar files, so i can't really speak to the utility of that workflow.

**Comment by maelle** [comment]
If you write such content, I'd suggest including it as a vcr vignette and using the same approach as other vcr chapters for adding it to the book.

**Comment by sckott** [comment]
PR in vcr repo
