### ISSUE TITLE
when would one use mocking not for testing

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#32]
Any example in an existing package?

**Comment by sckott** [comment]
- for caching outside of tests, e.g., i'm trying to build a http caching pkg on top of webmockr https://github.com/ropenscilabs/webmiddens 
- could use webmockr if you're on a plane with no internet

**Comment by maelle** [comment]
> could use webmockr if you're on a plane with no internet

Oooh I see and it might also be good for teaching about HTTP requests, by showing "this thing can play the role of an HTTP response"?

I'm looking at webmiddens README, very cool.

**Comment by sckott** [comment]
>  "this thing can play the role of an HTTP response"?

whats this thing? the cached response?

**Comment by sckott** [comment]
>  "this thing can play the role of an HTTP response"?

whats this thing? the cached response?

**Comment by maelle** [comment]
yes

**Comment by sckott** [comment]
okay. yes, i agree
