### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#33]
https://quickleft.com/blog/decreasing-vcr-dependency-webmock/

https://github.com/ropensci-books/http-testing/blob/a5dcb7ee0096f23088963f3cb5d47bf9de932e68/17-testing-considerations.Rmd#L55

**Comment by sckott** [comment]
ah, that blog is gone

**Comment by maelle** [comment]
ah too bad!

**Comment by sckott** [comment]
couldn't find another blog post along the same lines, just removing that link for now

**Comment by maelle** [comment]
what about the Internet Archive btw? although it might not be best practice to link to an Internet Archive link.

**Comment by sckott** [comment]
will look. 

I can never remember how the book is updated - looks like gh-pages is updated by a bot or so, do you know who runs that and how often its updated?

**Comment by maelle** [comment]
Any push to master, GH actions

**Comment by maelle** [comment]
See https://github.com/ropensci-books/http-testing/runs/500915282?check_suite_focus=true

**Comment by sckott** [comment]
ah ok, thanks!
