### ISSUE TITLE
Should the book also contain a reference to 'use_vcr'? 

### ISSUE THREAD

**Issue by DaveParr** [ropensci-books/http-testing#34]
Would it be relevant to put 'use_vcr' in the content here? I can't see a part that is referenced, and putting into the search doesn't give me any references. I'm also not seeing a clear 'getting started' section (though there is obviously some content related to config etc).

If not, feel free to close :)

**Comment by sckott** [comment]
Yes, I think it should. Probably in this chapter? https://books.ropensci.org/http-testing/vcr-usage.html @maelle any thoughts?

**Comment by maelle** [comment]
yes good suggestion, or in the future "whole game" vcr chapter. Thanks!

**Comment by sckott** [comment]
Cool. @maelle should @DaveParr PR the change or do you want to address it in your upcoming work on the boook?

**Comment by maelle** [comment]
I'll address it with bigger changes

**Comment by maelle** [comment]
will be tackled in #47
