### ISSUE TITLE
vcr: notes

### ISSUE THREAD

**Issue by sckott** [ropensci-books/http-testing#4]
- [ ] note that you can change the tests in a `vcr::use_cassette` block - doesn't affect the underlying use of cached response - though then tests could fail
- [ ] tell users to use `testthat::skip_on_cran` when using vcr tests that require secrets, as they can't have secrets on CRAN checks
- [ ] ...

**Comment by maelle** [comment]
>  tell users to use testthat::skip_on_cran when using vcr tests that require secrets, as they can't have secrets on CRAN checks

In that case one should simply setup a fake token, just to fool the package, as saved responses will be used.

**Comment by sckott** [comment]
true, but also id suggest skipping as many tests as possible on cran in the event of some random failure that gets an email from BDR

**Comment by maelle** [comment]
if you really want to skip as many tests as possible on CRAN

* skip them all
* have some minimal tests in tests/ and your actual tests in another folder?

**Comment by maelle** [comment]
I did suggest skipping all tests on CRAN in the CRAN chapter.
