### ISSUE TITLE
when comparing the three packages

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#51]
* http://veekaybee.github.io/2019/02/10/lockin/

* In presser docs https://r-lib.github.io/presser/articles/introduction.html#presser-vs-mocking "    Better test writing experience. This is subjective, and your mileage may vary."

**Comment by maelle** [comment]
* Something about debugging? with presser you can open your fake app in a browser / play with it with curl. that said with webmockr and httptest you have less needs for such debugging anyway.

**Comment by maelle** [comment]
Reg recording by hand https://github.com/maelle/exemplighratia/pull/3#discussion_r509861774

**Comment by maelle** [comment]
if you use vcr when testing for errors you use something that's entirely different, webmockr.

With httptest and presser the process for faking 502 errors is much more similar.

(on the topic of error, not that sequence of responses e.g. 502 502 200 are smooth with webmockr and presser but not httptest yet)

**Comment by sckott** [comment]
Interesting on the differences, thanks @maelle

**Comment by maelle** [comment]
reg debugging. how does one run code in the tests interactively whilst using the recorded response? I'm not too sure how I'd achieve that with vcr/httptest. With presser one would "just" start the app before running the code.

**Comment by maelle** [comment]
with httptest for debugging you'd use https://enpiar.com/r/httptest/reference/use_mock_api.html I suppose

@sckott how would one run code outside of tests, while still using a given cassette?

**Comment by maelle** [comment]
another point of interest, can you POST data and GET it.
* with presser yes, documented
* with webmockr how would you do that @sckott?
* with httptest cf what's done for vignettes, maybe other examples.

**Comment by sckott** [comment]
> how does one run code in the tests interactively whilst using the recorded response?

I do this by running the `vcr_configuration()` code block in the test helper file, and just change the paths to fixtures/files to reflect the directory you're in, e.,g., 

if this is what's in `helper-pkg.R`

```r
vcr::vcr_configure(dir = "../fixtures", write_disk_path = "../files")
```

and if you're current directory is the root of the package and tests are are in `tests/`, then run 

```r
vcr::vcr_configure(dir = "tests/fixtures", write_disk_path = "tests/files")
```

and then when you run http requests wrapped in `use_cassette` you'll use the recorded fixtures

**Comment by sckott** [comment]
answer about post then get in slack

**Comment by maelle** [comment]
Oooh could one improve this by

- switching back to helper not setup. Helper is no longer recommended but still supported and loaded by load_all(). Maybe not worth the switch though. 
- have tests live in testthat/fixtures instead this way one would use testthat::test_path() to refer to the path which works in interactive mode too. Or some equivalent function. This way no need to fix the configuration 🤔

**Comment by sckott** [comment]
> have tests live in testthat/fixtures

I don't like this idea. 

We can keep thinking though

**Comment by maelle** [comment]
Yeah one would just need a function that returns the right path to tests/fixtures no matter where it is called from (from tests/testthat or from the root)

**Comment by sckott** [comment]
Right
