### ISSUE TITLE
Edit button points to "master" branch

### ISSUE THREAD

**Issue by dpprdan** [ropensci-books/http-testing#58]
The edit button in the header still points to the "master" branch instead of main, i.e. one lands here <https://github.com/ropensci-books/http-testing/edit/master/index.Rmd> instead of <https://github.com/ropensci-books/http-testing/edit/main/index.Rmd>.
![grafik](https://user-images.githubusercontent.com/1423562/97728068-6468aa00-1ad1-11eb-8fd7-835f58954b51.png)

**Comment by dpprdan** [comment]
There are still a few references to "master", but I don't think they cause this.
https://github.com/ropensci-books/http-testing/search?q=master

Could "master" be hardcoded in the gitbook template?

**Comment by sckott** [comment]
thanks @dpprdan for pointing this out!

I think @maelle is the best person to handle this, she changed to use downlit recently which I don't know anything about. she should be back to work monday

**Comment by dpprdan** [comment]
🤔 AFAIU Commit 2a7b57c9ff6da638ffc5b166f3f9c63fe708dbe3 should have fixed this and it has been run here: https://github.com/ropensci-books/http-testing/actions/runs/291351293

@sckott Not sure I follow how downlit could have anything to do with this. In any case there is no rush from my side, just wanted to let y'all know.

**Comment by maelle** [comment]
good catch. not sure why the change didn't happen, but now I've re-launched a build with a minimal unrelated commit and it works :woman_shrugging: thanks a ton for the report!
