### ISSUE TITLE
clarify scope

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#61]
The package does not need to wrap an actual web API, it just needs to interact with the web. 

Thanks @llrs

**Comment by sckott** [comment]
could be localhost too 😸

**Comment by llrs** [comment]
oh, then I will need to read more about the packages and the solutions they propose.
Currently I test directly against the web in a couple of packages and expected it to be more complicated. Thanks @sckott for webmockr and vcr (I'll probably use vcr)

**Comment by sckott** [comment]
thx - maëlle is an author now on vcr too :)

**Comment by llrs** [comment]
Much clearer. Thanks @maelle I'm sure the alert "web resource, even poorly documented ones." will help more people say: hey, this is for me! :smiley:
