### ISSUE TITLE
footer text

### ISSUE THREAD

**Issue by sckott** [ropensci-books/http-testing#69]
built on built on

<img width="567" alt="Screen Shot 2020-12-10 at 5 44 52 PM" src="https://user-images.githubusercontent.com/577668/101850891-78132180-3b0f-11eb-964d-11ffa044091b.png">

**Comment by maelle** [comment]
I'll wait for developments in https://github.com/rstudio/bookdown/issues/1011 before looking at this.

**Comment by maelle** [comment]
magically fixed, actually
