### ISSUE TITLE
mention tools helping see credential leaks

### ISSUE THREAD

**Issue by maelle** [ropensci-books/http-testing#80]
h/t @Bisaloo

https://github.com/eth0izzle/shhgit

Maybe git commit hook?

**Comment by maelle** [comment]
https://github.com/Yelp/detect-secrets

**Comment by llrs** [comment]
Maybe worth mentioning [git-secrets](https://git-secret.io/) ([repo](https://github.com/awslabs/git-secrets))

**Comment by maelle** [comment]
@llrs thanks for this and the other useful comments, I'll try to work on them as soon as possible! :pray:
