### ISSUE TITLE
Link to webmiddens is broken

### ISSUE THREAD

**Issue by Bisaloo** [ropensci-books/http-testing#85]
On https://books.ropensci.org/http-testing/graceful.html, the link to webmiddens is broken: https://docs.ropensci.org/webmiddens/.

I'm not sure how to fix it myself since I didn't follow the latest policies about the various rOpenSci GitHub orgs. My guess is that ropenscilabs packages are now excluded from the documentation auto-deploy process(?). The link listed at https://github.com/sckott/webmiddens (https://sckott.ropensci.org/webmiddens) fails as well.

**Comment by Bisaloo** [comment]
Ah yes, just seeing now that webmiddens is currently hosted on Scott's personal account. That explains the situation.

**Comment by maelle** [comment]
Thank you!
@sckott could you please fix the link?

**Comment by sckott** [comment]
updated the link, note that webmiddens is probably not going to see any more work on it, it's not clear yet if there's any advantage over just using memoise
