### ISSUE TITLE
How to share cassettes between tests?

### ISSUE THREAD

**Issue by dpprdan** [ropensci-books/http-testing#88]
In [chapter 12.1](https://books.ropensci.org/http-testing/cran-preparedness.html?#running-tests-on-cran) it says:

> Share cassettes / mock files / recorded responses between tests.

How would I share cassettes with vcr? (Not least because [`vcr::check_cassette_names()`](https://docs.ropensci.org/vcr/reference/check_cassette_names.html) checks for duplicate cassette names.)

**Comment by maelle** [comment]
Ah good question, maybe the checking of cassette names should have an argument to allow duplicates @sckott?

**Comment by sckott** [comment]
reinstall vcr, see https://docs.ropensci.org/vcr/reference/check_cassette_names.html

**Comment by maelle** [comment]
Awesome! I would find "allow_duplicates" a better name than "allowed_duplicates". 

Can this issue be closed?

**Comment by dpprdan** [comment]
> Can this issue be closed?

Does this need some more explanation in the book? Regarding my orginial question?

**Comment by sckott** [comment]
Yes, I think it does need more explanation. Would you be willing to send a PR?

**Comment by dpprdan** [comment]
Darn, me and my big mouth. 😉 
I'll see if I can come up with something. 😄
