### ISSUE TITLE
add github source url

### ISSUE THREAD

**Issue by maxheld83** [ropensci-books/http-testing#89]
I'm not sure whether I'm just super dense, but I couldn't find the customary gh link to the source on book website.

The righthand sidebar seemed to miss some entries compared with https://adv-r.hadley.nz (which is also `bs4_book`?)

**Comment by maelle** [comment]
You are right (thanks for opening the issue!), it is a limitation to `bs4_book` for repos whose default branch is not master.

https://github.com/rstudio/bookdown/pull/1036

**Comment by maelle** [comment]
https://github.com/rstudio/bookdown/pull/1036 has been merged, I'll fix the repo URL here shortly.
